/**
 * Extended keyword collection for maximum SEO coverage
 * Targeting primary, secondary, and long-tail keywords for resume and resume builder
 */

export const extendedSeoKeywords = {
  // 50+ Resume-focused primary keywords
  resumePrimaryKeywords: [
    "resume",
    "resume writing",
    "resume format", 
    "resume examples",
    "resume tips",
    "resume help",
    "resume advice",
    "resume guide",
    "resume samples",
    "resume objective",
    "resume summary", 
    "resume skills",
    "resume experience",
    "resume education",
    "resume sections",
    "resume layout",
    "resume design",
    "resume structure",
    "resume content",
    "resume keywords",
    "resume optimization",
    "resume improvement",
    "resume enhancement",
    "resume review",
    "resume critique",
    "resume analysis",
    "resume evaluation",
    "resume assessment",
    "resume feedback",
    "resume suggestions",
    "resume recommendations",
    "resume best practices",
    "resume standards",
    "resume requirements",
    "resume checklist",
    "resume mistakes",
    "resume errors",
    "resume problems",
    "resume solutions",
    "resume strategies",
    "resume techniques",
    "resume methods",
    "resume approaches",
    "resume tactics",
    "resume success",
    "resume effectiveness",
    "resume impact",
    "resume results",
    "resume outcomes",
    "resume performance"
  ],

  // 50+ Resume Builder focused keywords  
  resumeBuilderKeywords: [
    "resume builder",
    "resume maker", 
    "resume creator",
    "resume generator",
    "resume designer",
    "resume editor",
    "resume writer",
    "resume composer",
    "resume formatter",
    "resume constructor",
    "resume compiler",
    "resume assembler",
    "resume producer",
    "resume developer",
    "resume architect",
    "resume craftsman",
    "resume specialist",
    "resume expert",
    "resume professional",
    "resume consultant", 
    "resume service",
    "resume platform",
    "resume tool",
    "resume software", 
    "resume application",
    "resume program",
    "resume system",
    "resume solution",
    "resume technology",
    "resume innovation",
    "resume automation",
    "resume intelligence",
    "resume assistance",
    "resume support",
    "resume guidance",
    "resume coaching",
    "resume mentoring",
    "resume training",
    "resume education",
    "resume learning",
    "resume development",
    "resume improvement",
    "resume enhancement",
    "resume optimization",
    "resume maximization",
    "resume personalization",
    "resume customization",
    "resume tailoring",
    "resume adaptation",
    "resume modification",
    "resume transformation"
  ],

  // 100+ Long-tail keyword variations
  longTailVariations: [
    "how to write a professional resume",
    "best way to format a resume",
    "resume writing tips for beginners",
    "professional resume examples 2025",
    "modern resume templates free",
    "ATS friendly resume format",
    "resume builder with AI assistance", 
    "free professional resume maker online",
    "resume creator for job applications",
    "best resume format for 2025",
    "resume writing guide step by step",
    "professional resume templates download",
    "resume maker with cover letter",
    "AI powered resume optimization",
    "free resume builder no registration",
    "resume creator for career change",
    "professional CV maker online",
    "resume builder for students", 
    "executive resume writing service",
    "technical resume examples",
    "creative resume design ideas",
    "resume format for freshers",
    "experienced professional resume",
    "manager level resume examples",
    "director resume template",
    "VP resume writing tips",
    "C-suite executive resume",
    "startup resume examples",
    "remote work resume format",
    "freelancer resume template",
    "consultant resume examples",
    "engineer resume format",
    "software developer resume",
    "data scientist resume template",
    "product manager resume example",
    "marketing manager resume",
    "sales professional resume",
    "finance manager resume",
    "accounting professional resume",
    "healthcare worker resume",
    "nurse resume template",
    "doctor resume format",
    "teacher resume examples",
    "education professional resume",
    "nonprofit resume template",
    "government job resume format",
    "federal resume writing",
    "military resume examples",
    "veteran resume template",
    "international resume format",
    "resume for overseas jobs",
    "global career resume",
    "multinational resume template",
    "bilingual resume format",
    "resume with language skills",
    "cultural adaptation resume",
    "cross-cultural resume writing",
    "diversity focused resume",
    "inclusive resume examples",
    "accessibility friendly resume",
    "universal resume design",
    "standard resume format",
    "traditional resume layout",
    "conventional resume structure",
    "classic resume design",
    "timeless resume format",
    "professional resume appearance",
    "business resume template",
    "corporate resume format",
    "industry specific resume",
    "sector focused resume",
    "niche market resume",
    "specialized career resume",
    "expert level resume",
    "senior professional resume",
    "leadership resume examples",
    "management resume template",
    "supervisor resume format",
    "team leader resume",
    "coordinator resume example",
    "analyst resume template", 
    "specialist resume format",
    "technician resume example",
    "operator resume template",
    "assistant resume format",
    "associate resume example",
    "entry level resume template",
    "graduate resume format", 
    "intern resume example",
    "trainee resume template",
    "apprentice resume format",
    "junior professional resume",
    "career starter resume",
    "first job resume template",
    "college graduate resume",
    "university student resume",
    "high school resume format",
    "academic resume template",
    "research resume example",
    "scholarly resume format",
    "publication heavy resume",
    "conference presentation resume",
    "grant writing resume",
    "academic achievement resume",
    "teaching focused resume",
    "learning development resume",
    "curriculum design resume",
    "instructional resume template",
    "training specialist resume",
    "corporate trainer resume",
    "professional development resume"
  ],

  // 50+ AI and Technology keywords
  aiTechKeywords: [
    "AI resume builder",
    "artificial intelligence resume",
    "machine learning resume creator", 
    "smart resume generator",
    "intelligent resume maker",
    "automated resume builder",
    "AI powered resume writer",
    "machine learning resume optimization",
    "natural language resume processing",
    "AI resume content generation",
    "intelligent resume formatting",
    "automated resume review",
    "AI resume keyword optimization", 
    "machine learning job matching",
    "smart resume personalization",
    "AI career guidance",
    "intelligent job recommendations",
    "automated interview preparation",
    "AI powered career coaching", 
    "machine learning skill assessment",
    "smart professional development",
    "AI resume performance analytics",
    "intelligent career path planning",
    "automated networking suggestions",
    "AI job search optimization",
    "machine learning market analysis",
    "smart salary negotiation",
    "AI interview practice",
    "intelligent resume scoring",
    "automated ATS optimization",
    "AI keyword suggestion",
    "machine learning content enhancement",
    "smart formatting recommendations",
    "AI grammar checking",
    "intelligent spell checking",
    "automated proofreading",
    "AI style optimization",
    "machine learning readability analysis",
    "smart content organization", 
    "AI section optimization",
    "intelligent bullet point generation",
    "automated achievement quantification",
    "AI impact measurement",
    "machine learning result prediction",
    "smart success forecasting",
    "AI career trajectory analysis",
    "intelligent growth planning",
    "automated skill gap analysis",
    "AI learning recommendations",
    "machine learning certification suggestions"
  ]
};

// Industry-specific keyword clusters (50+ keywords each)
export const industryKeywordClusters = {
  technology: [
    "software engineer resume",
    "web developer resume", 
    "full stack developer resume",
    "frontend developer resume",
    "backend developer resume",
    "mobile app developer resume",
    "iOS developer resume",
    "Android developer resume",
    "React developer resume",
    "Angular developer resume", 
    "Vue.js developer resume",
    "Node.js developer resume",
    "Python developer resume",
    "Java developer resume",
    "JavaScript developer resume",
    "TypeScript developer resume",
    "C++ developer resume",
    "C# developer resume",
    "PHP developer resume",
    "Ruby developer resume",
    "Go developer resume",
    "Rust developer resume",
    "Swift developer resume",
    "Kotlin developer resume",
    "Scala developer resume",
    "DevOps engineer resume",
    "Cloud engineer resume",
    "AWS developer resume", 
    "Azure developer resume",
    "Google Cloud resume",
    "Kubernetes engineer resume",
    "Docker specialist resume",
    "CI/CD engineer resume",
    "Site reliability engineer resume",
    "Platform engineer resume",
    "Infrastructure engineer resume",
    "Security engineer resume",
    "Cybersecurity analyst resume",
    "Penetration tester resume",
    "Information security resume",
    "Network engineer resume", 
    "System administrator resume",
    "Database administrator resume",
    "Data engineer resume",
    "Data scientist resume",
    "Machine learning engineer resume",
    "AI researcher resume",
    "Deep learning engineer resume",
    "Computer vision engineer resume",
    "NLP engineer resume"
  ],

  healthcare: [
    "registered nurse resume",
    "nurse practitioner resume",
    "clinical nurse resume",
    "ICU nurse resume",
    "ER nurse resume",
    "surgical nurse resume",
    "pediatric nurse resume",
    "oncology nurse resume",
    "cardiac nurse resume",
    "psychiatric nurse resume",
    "home health nurse resume",
    "travel nurse resume",
    "nurse manager resume",
    "charge nurse resume",
    "staff nurse resume", 
    "LPN resume",
    "CNA resume",
    "medical assistant resume",
    "physician assistant resume",
    "nurse anesthetist resume",
    "nurse midwife resume",
    "clinical nurse specialist resume",
    "doctor resume",
    "physician resume",
    "surgeon resume",
    "internist resume",
    "cardiologist resume",
    "neurologist resume",
    "psychiatrist resume",
    "radiologist resume",
    "pathologist resume",
    "anesthesiologist resume",
    "emergency medicine physician resume",
    "family medicine doctor resume",
    "pediatrician resume",
    "obstetrician resume",
    "gynecologist resume",
    "urologist resume",
    "orthopedic surgeon resume",
    "plastic surgeon resume",
    "dermatologist resume",
    "ophthalmologist resume",
    "ENT doctor resume",
    "medical technologist resume",
    "lab technician resume",
    "radiologic technologist resume",
    "ultrasound technician resume",
    "pharmacy technician resume",
    "pharmacist resume",
    "physical therapist resume"
  ],

  finance: [
    "financial analyst resume",
    "investment banker resume",
    "portfolio manager resume",
    "financial advisor resume",
    "wealth manager resume",
    "private banker resume",
    "commercial banker resume",
    "investment advisor resume",
    "financial planner resume",
    "risk analyst resume",
    "credit analyst resume",
    "equity analyst resume",
    "research analyst resume",
    "quantitative analyst resume",
    "derivatives trader resume",
    "fixed income trader resume",
    "forex trader resume",
    "commodities trader resume",
    "hedge fund manager resume",
    "private equity associate resume",
    "venture capital analyst resume",
    "investment associate resume",
    "corporate finance analyst resume",
    "M&A analyst resume",
    "valuation analyst resume",
    "financial controller resume",
    "finance manager resume",
    "accounting manager resume",
    "senior accountant resume",
    "staff accountant resume",
    "bookkeeper resume",
    "payroll specialist resume",
    "accounts receivable resume",
    "accounts payable resume",
    "tax accountant resume",
    "tax advisor resume",
    "audit manager resume",
    "internal auditor resume",
    "external auditor resume",
    "compliance officer resume",
    "financial reporting manager resume",
    "budget analyst resume",
    "cost accountant resume",
    "management accountant resume",
    "forensic accountant resume",
    "CPA resume",
    "CFA resume",
    "FRM resume",
    "actuary resume"
  ]
};