// Comprehensive SEO keywords and metadata configurations
export const seoKeywords = {
  // ── Short / head keywords (high volume, 1-2 words) ──────────────────────────
  primary: [
    "resume builder",
    "free resume builder",
    "ai resume builder",
    "resume maker",
    "resume templates",
    "online resume builder",
    "CV maker",
    "ATS resume",
    "resume creator",
    "resume generator",
    "professional resume",
    "create resume",
    "resume writer",
    "resume tool",
    "resume app",
    "CV builder",
    "CV creator",
    "CV templates",
    "resume format",
    "resume design",
  ],

  // ── Medium keywords (2-4 words) ──────────────────────────────────────────────
  secondary: [
    "free resume maker",
    "free cv maker",
    "free resume templates",
    "resume builder free",
    "online cv builder",
    "ats resume builder",
    "ats friendly resume",
    "ats resume checker",
    "resume builder online",
    "resume maker online",
    "resume builder 2025",
    "best resume builder",
    "ai resume maker",
    "ai cv builder",
    "professional cv builder",
    "modern resume builder",
    "simple resume builder",
    "quick resume maker",
    "instant resume builder",
    "resume builder no sign up",
    "resume builder no credit card",
    "free resume download",
    "resume pdf builder",
    "ats optimized resume",
    "free professional resume",
    "free online cv",
    "free resume website",
    "create cv online",
    "create resume online",
    "resume builder open source",
  ],

  // ── Competitor alternative keywords (high purchase intent) ──────────────────
  competitorAlternatives: [
    "free zety alternative",
    "zety free alternative",
    "zety alternative free",
    "free alternative to zety",
    "resume builder like zety but free",
    "free novoresume alternative",
    "novoresume free alternative",
    "free alternative to novoresume",
    "free resume io alternative",
    "resume io free alternative",
    "free alternative to resume io",
    "free kickresume alternative",
    "free canva resume alternative",
    "free linkedin resume builder alternative",
    "free indeed resume builder",
    "resume builder free no watermark",
    "resume builder free no subscription",
    "resume builder free to download",
    "resume builder actually free",
    "resume builder 100 percent free",
    "resume builder completely free",
    "open source resume builder free",
    "resume builder free forever",
    "best free resume builder no hidden fees",
    "resume builder that doesnt charge to download",
    "free resume builder unlike zety",
  ],

  // ── Industry-specific keywords ───────────────────────────────────────────────
  industries: [
    "software engineer resume",
    "software developer resume",
    "software engineer resume template",
    "data scientist resume",
    "data analyst resume",
    "full stack developer resume",
    "frontend developer resume",
    "backend developer resume",
    "devops engineer resume",
    "machine learning engineer resume",
    "product manager resume",
    "project manager resume",
    "marketing resume",
    "digital marketing resume",
    "sales resume",
    "finance resume",
    "accounting resume",
    "investment banking resume",
    "healthcare resume",
    "nursing resume",
    "doctor resume",
    "pharmacist resume",
    "teacher resume",
    "education resume",
    "fresher resume",
    "freshers resume format",
    "student resume",
    "entry level resume",
    "MBA resume",
    "executive resume",
    "C suite resume",
    "manager resume",
    "consultant resume",
    "business analyst resume",
    "UX designer resume",
    "graphic designer resume",
    "content writer resume",
    "HR resume",
    "operations manager resume",
    "civil engineer resume",
    "mechanical engineer resume",
    "electrical engineer resume",
    "cybersecurity resume",
    "cloud engineer resume",
    "remote work resume",
  ],

  // ── Feature-based keywords ───────────────────────────────────────────────────
  features: [
    "ats friendly resume builder",
    "ats resume checker free",
    "ats resume scanner",
    "ats resume optimizer",
    "ats compliant resume",
    "applicant tracking system resume",
    "resume keyword optimizer",
    "resume score checker",
    "ai powered resume writing",
    "ai resume suggestions",
    "ai generated resume",
    "resume bullet point generator",
    "resume summary generator",
    "cover letter generator",
    "resume spell checker",
    "resume formatting tool",
    "resume pdf download",
    "resume without watermark",
    "multiple resume templates",
    "customizable resume template",
  ],

  // ── Long-tail keywords (question & intent based, 5+ words) ──────────────────
  longTail: [
    // How-to intent (high informational → conversion)
    "how to make a resume for free",
    "how to create a professional resume",
    "how to build a resume online free",
    "how to write a resume step by step",
    "how to make an ats friendly resume",
    "how to pass ats with your resume",
    "how to make a resume with no experience",
    "how to write a resume summary",
    "how to write a resume objective",
    "how to format a resume for 2025",
    "what to put on a resume with no experience",
    "what skills should i put on my resume",
    "what is the best format for a resume",
    "which resume builder is completely free",
    "which resume builder is best for freshers",
    "which resume builder does not charge to download",

    // Best / top intent
    "best free resume builder 2025",
    "best ai resume builder free",
    "best free online resume builder no sign up",
    "best free ats resume builder online",
    "best resume builder that is actually free",
    "best resume maker for software engineers",
    "best resume builder for freshers",
    "best resume builder for students",
    "best resume builder for career change",
    "best free cv maker for professionals",
    "top 10 free resume builders 2025",
    "best free resume builder reddit 2025",

    // Specific use-case long tails
    "free resume builder for software engineer",
    "free resume builder for freshers india",
    "free resume builder for college students",
    "free resume builder for nurses",
    "free resume builder for teachers",
    "free resume builder for marketing jobs",
    "free resume builder no watermark pdf download",
    "free resume builder with cover letter",
    "free resume builder with linkedin import",
    "ai resume builder free no subscription",
    "ai resume builder that writes for you",
    "ai resume builder free for students",
    "create professional resume in 5 minutes free",
    "create ats friendly resume online free",
    "create resume online free no sign up",
    "build resume for free and download as pdf",
    "make resume online free download pdf",
    "professional resume template free download word",
    "professional resume template free download pdf",
    "resume template free download for freshers",
    "free resume format for experienced professionals",
    "ats resume format free download",
    "resume builder that passes applicant tracking systems",
    "free ai powered resume builder for job seekers",
    "automated resume builder with ai suggestions free",
    "free resume creator for entry level positions",
    "modern resume builder free with ai assistance",
    "resume builder for remote jobs free",
    "free resume builder for international jobs",
    "free resume builder for government jobs",
    "free professional cv builder online no sign up",
    "open source free resume builder with ai",
    "resume builder free forever no hidden fees",

    // Competitor comparison long tails
    "better than zety resume builder free",
    "free resume builder better than novoresume",
    "free resume download without zety subscription",
    "resume builder free to use and download",
    "resume builder with no paywall",
    "resume builder completely free no credit card",
    "free alternative to paid resume builders",
  ],

  // ── Trending / niche keywords 2025 ───────────────────────────────────────────
  trending2025: [
    "ai resume builder 2025",
    "free resume builder 2025",
    "best resume format 2025",
    "ats resume 2025",
    "resume tips 2025",
    "resume keywords 2025",
    "chatgpt resume builder",
    "ai generated resume free",
    "resume builder with chatgpt",
    "llm powered resume builder",
    "resume builder for ai jobs",
    "tech resume 2025",
    "resume for remote jobs 2025",
    "free resume builder india",
    "free resume builder uk",
    "free resume builder canada",
    "free resume builder australia",
    "best resume builder for india",
    "resume builder for naukri",
    "resume for linkedin 2025",
  ],
};

// SEO-optimized descriptions for different pages
export const seoDescriptions = {
  home: "The best free AI resume builder — create professional ATS-optimized resumes in minutes. Unlike Zety, Novoresume, and Resume.io that charge you to download, Resumy is 100% free forever. No hidden fees, no watermarks, no credit card. Start building today!",

  analyzeResume: "Analyze and optimize your resume for free with Resumy's AI-powered resume analyzer. Get instant ATS compatibility score, keyword gaps, and actionable improvements — completely free.",

  templates: "Choose from professional ATS-optimized resume templates for every industry. Modern, clean designs that pass applicant tracking systems. 100% free download, no watermark, no subscription.",

  features: "Discover Resumy's free AI resume features: ATS optimization, keyword analysis, professional templates, real-time editing, industry-specific formatting, and AI bullet point suggestions. Everything free, always.",
};

// Meta titles optimized for different pages
export const seoTitles = {
  home: "Resumy - #1 Free AI Resume Builder | No Paywall, No Subscription, No Credit Card",
  analyzeResume: "Free AI Resume Analyzer & ATS Checker | Optimize Your Resume - Resumy",
  templates: "Free Professional Resume Templates | ATS-Optimized, No Watermark - Resumy",
  features: "Free AI Resume Builder Features | ATS Optimization & Smart Tools - Resumy",
};
