import ResumeTemplate1 from "../components/resumetemplates/ResumeTemplate1";
import ResumeTemplate2 from "../components/resumetemplates/ResumeTemplate2";
import ResumeTemplate3 from "../components/resumetemplates/ResumeTemplate3";

const templates = [
  {
    name: "Classic (Template 1)",
    component: ResumeTemplate1,
    fields: [
      { name: "name", label: "Full Name", type: "text", placeholder: "John Doe" },
      { name: "address", label: "Address (line 1)", type: "text", placeholder: "123 Broadway ● City, State 12345" },
      { name: "address2", label: "Address (line 2)", type: "text", placeholder: "123 Pleasant Lane ● City, State 12345" },
      { name: "phone", label: "Phone", type: "tel", placeholder: "(001) - 899 - 9999" },
      { name: "email", label: "Email", type: "email", placeholder: "john@resumy.com" },
      // Education section
      { name: "education_heading", label: "Education Heading", type: "text", placeholder: "EDUCATION" },
      { name: "education_university", label: "Education - University", type: "text", placeholder: "University of California, Berkeley" },
      { name: "education_degree", label: "Education - Degree", type: "text", placeholder: "B.S. in Computer Science & Engineering" },
      { name: "education_minor", label: "Education - Minor", type: "text", placeholder: "Minor in Linguistics" },
      { name: "education_honors1", label: "Education - Honor 1", type: "text", placeholder: "Member of Eta Kappa Nu" },
      { name: "education_honors2", label: "Education - Honor 2", type: "text", placeholder: "Member of Upsilon Pi Epsilon" },
      { name: "education_gpa", label: "Education - GPA", type: "text", placeholder: "Overall GPA: 5.678" },
      { name: "education_date", label: "Education - Date", type: "text", placeholder: "June 2004" },
      // Experience 1
      { name: "exp1_heading", label: "Experience 1 Heading", type: "text", placeholder: "EXPERIENCE" },
      { name: "exp1_company", label: "Experience 1 - Company", type: "text", placeholder: "ACME, Inc" },
      { name: "exp1_dates", label: "Experience 1 - Dates", type: "text", placeholder: "October 2010 - Present" },
      { name: "exp1_title", label: "Experience 1 - Title", type: "text", placeholder: "Web Developer" },
      { name: "exp1_location", label: "Experience 1 - Location", type: "text", placeholder: "Palo Alto, CA" },
      { name: "exp1_bullets_heading", label: "Experience 1 Bullets Heading", type: "text", placeholder: "Responsibilities" },
      { name: "exp1_bullets", label: "Experience 1 Bullets", type: "bullets", placeholder: "Add bullet points for Experience 1", repeatable: true },
      // Experience 2
      { name: "exp2_company", label: "Experience 2 - Company", type: "text", placeholder: "AJAX Hosting" },
      { name: "exp2_dates", label: "Experience 2 - Dates", type: "text", placeholder: "December 2009 - October 2010" },
      { name: "exp2_title", label: "Experience 2 - Title", type: "text", placeholder: "Lead Developer" },
      { name: "exp2_location", label: "Experience 2 - Location", type: "text", placeholder: "Austin, TX" },
      { name: "exp2_bullets_heading", label: "Experience 2 Bullets Heading", type: "text", placeholder: "Responsibilities" },
      { name: "exp2_bullets", label: "Experience 2 Bullets", type: "bullets", placeholder: "Add bullet points for Experience 2", repeatable: true },
      // Experience 3
      { name: "exp3_company", label: "Experience 3 - Company", type: "text", placeholder: "TinySoft" },
      { name: "exp3_dates", label: "Experience 3 - Dates", type: "text", placeholder: "January 2008 - April 2010" },
      { name: "exp3_title", label: "Experience 3 - Title", type: "text", placeholder: "Web Designer & Developer" },
      { name: "exp3_location", label: "Experience 3 - Location", type: "text", placeholder: "Gainesville, GA" },
      { name: "exp3_bullets_heading", label: "Experience 3 Bullets Heading", type: "text", placeholder: "Responsibilities" },
      { name: "exp3_bullets", label: "Experience 3 Bullets", type: "bullets", placeholder: "Add bullet points for Experience 3", repeatable: true },
      // Technical Strengths
      { name: "skills_heading", label: "Technical Strengths Heading", type: "text", placeholder: "TECHNICAL STRENGTHS" },
      { name: "skills_languages", label: "Skills - Languages", type: "text", placeholder: "Prolog, Haskell, AWK, Erlang, Scheme, ML" },
      { name: "skills_protocols", label: "Skills - Protocols & APIs", type: "text", placeholder: "XML, JSON, SOAP, REST" },
      { name: "skills_databases", label: "Skills - Databases", type: "text", placeholder: "MySQL, PostgreSQL, Microsoft SQL" },
      { name: "skills_tools", label: "Skills - Tools", type: "text", placeholder: "SVN, Vim, Emacs" },
      { name: "skills", label: "Technical Strengths Bullets", type: "bullets", placeholder: "Add skills", repeatable: true },
    ],
    dummy: {
      name: "JOHN DOE",
      address: "123 Broadway ● City, State 12345",
      address2: "123 Pleasant Lane ● City, State 12345",
      phone: "(001) - 899 - 9881",
      email: "john@resumy.com",
      education_heading: "EDUCATION",
      education_university: "University of California, Berkeley",
      education_degree: "B.S. in Computer Science & Engineering",
      education_minor: "Minor in Linguistics",
      education_honors1: "Member of Eta Kappa Nu",
      education_honors2: "Member of Upsilon Pi Epsilon",
      education_gpa: "Overall GPA: 5.678",
      education_date: "June 2004",
      exp1_heading: "EXPERIENCE",
      exp1_company: "ACME, Inc",
      exp1_dates: "October 2010 - Present",
      exp1_title: "Web Developer",
      exp1_location: "Palo Alto, CA",
      exp1_bullets_heading: "Responsibilities",
      exp1_bullets: [
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        "Donec et mollis dolor.",
      ],
      exp2_company: "AJAX Hosting",
      exp2_dates: "December 2009 - October 2010",
      exp2_title: "Lead Developer",
      exp2_location: "Austin, TX",
      exp2_bullets_heading: "Responsibilities",
      exp2_bullets: [
        "Aenean ut gravida lorem.",
        "Curabitur dapibus enim sit amet elit pharetra tincidunt.",
      ],
      exp3_company: "TinySoft",
      exp3_dates: "January 2008 - April 2010",
      exp3_title: "Web Designer & Developer",
      exp3_location: "Gainesville, GA",
      exp3_bullets_heading: "Responsibilities",
      exp3_bullets: [
        "Vivamus fermentum semper porta.",
        "Maecenas convallis ullamcorper ultricies.",
      ],
      skills_heading: "TECHNICAL STRENGTHS",
      skills_languages: "Prolog, Haskell, AWK, Erlang, Scheme, ML",
      skills_protocols: "XML, JSON, SOAP, REST",
      skills_databases: "MySQL, PostgreSQL, Microsoft SQL",
      skills_tools: "SVN, Vim, Emacs",
    },
    fieldsPerPage: 10,
  },
  {
    name: "Modern (Template 2)",
    component: ResumeTemplate2,
    fields: [
      { name: "name", label: "Full Name", type: "text", placeholder: "Alexandra Smith" },
      { name: "title", label: "Title", type: "text", placeholder: "Curriculum Vitae" },
      { name: "address", label: "Address", type: "text", placeholder: "1234 Elm Street, Springfield, IL 62704" },
      { name: "phone", label: "Phone", type: "tel", placeholder: "(555) 123-4567" },
      { name: "email", label: "Email", type: "email", placeholder: "alexandra.smith@email.com" },
      { name: "website", label: "Website", type: "text", placeholder: "www.alexandrasmith.dev" },
      { name: "research_heading", label: "Research Heading", type: "text", placeholder: "Doctoral Research" },
      { name: "research_title", label: "Research Title", type: "text", placeholder: "“Exploring Quantum Computing Algorithms for Enhanced Cryptography”" },
      { name: "research_desc", label: "Research Description", type: "textarea", placeholder: "My doctoral research focused on the development and analysis of quantum algorithms..." },
      { name: "exp1_heading", label: "Experience 1 Heading", type: "text", placeholder: "Work Experience" },
      { name: "exp1_company", label: "Experience 1 - Company", type: "text", placeholder: "Innovatech Solutions" },
      { name: "exp1_dates", label: "Experience 1 - Dates", type: "text", placeholder: "Mar 2020 – Present" },
      { name: "exp1_title", label: "Experience 1 - Title", type: "text", placeholder: "Lead Software Engineer" },
      { name: "exp1_desc", label: "Experience 1 - Description", type: "textarea", placeholder: "Leading a team of 8 engineers..." },
      { name: "exp1_bullets", label: "Experience 1 Bullets", type: "bullets", placeholder: "Add bullet points for Experience 1", repeatable: true },
      { name: "exp2_company", label: "Experience 2 - Company", type: "text", placeholder: "NextGen Analytics" },
      { name: "exp2_dates", label: "Experience 2 - Dates", type: "text", placeholder: "Jul 2017 – Feb 2020" },
      { name: "exp2_title", label: "Experience 2 - Title", type: "text", placeholder: "Data Scientist" },
      { name: "exp2_desc", label: "Experience 2 - Description", type: "textarea", placeholder: "Developed machine learning models..." },
      { name: "exp2_bullets", label: "Experience 2 Bullets", type: "bullets", placeholder: "Add bullet points for Experience 2", repeatable: true },
      { name: "exp3_company", label: "Experience 3 - Company", type: "text", placeholder: "Springfield University" },
      { name: "exp3_dates", label: "Experience 3 - Dates", type: "text", placeholder: "Sep 2015 – Jun 2017" },
      { name: "exp3_title", label: "Experience 3 - Title", type: "text", placeholder: "Graduate Research Assistant" },
      { name: "exp3_desc", label: "Experience 3 - Description", type: "textarea", placeholder: "Assisted in research on distributed systems..." },
      { name: "exp3_bullets", label: "Experience 3 Bullets", type: "bullets", placeholder: "Add bullet points for Experience 3", repeatable: true },
      { name: "references_heading", label: "References Heading", type: "text", placeholder: "References" },
      { name: "ref1_name", label: "Reference 1 - Name", type: "text", placeholder: "Dr. Emily Carter" },
      { name: "ref1_affil", label: "Reference 1 - Affiliation", type: "text", placeholder: "Department of Computer Science" },
      { name: "ref1_org", label: "Reference 1 - Organization", type: "text", placeholder: "Springfield University" },
      { name: "ref1_phone", label: "Reference 1 - Phone", type: "text", placeholder: "+1 (217) 555-7890 (Work)" },
      { name: "ref2_name", label: "Reference 2 - Name", type: "text", placeholder: "Dr. Michael Lee" },
      { name: "ref2_affil", label: "Reference 2 - Affiliation", type: "text", placeholder: "Chief Data Scientist" },
      { name: "ref2_org", label: "Reference 2 - Organization", type: "text", placeholder: "NextGen Analytics" },
      { name: "ref2_phone", label: "Reference 2 - Phone", type: "text", placeholder: "+1 (312) 555-2468 (Work)" },
      { name: "education_heading", label: "Education Heading", type: "text", placeholder: "Education" },
      { name: "edu1_years", label: "Education 1 - Years", type: "text", placeholder: "2015 – 2020" },
      { name: "edu1_degree", label: "Education 1 - Degree", type: "text", placeholder: "Ph.D. in Computer Science" },
      { name: "edu1_school", label: "Education 1 - School", type: "text", placeholder: "Springfield University" },
      { name: "edu2_years", label: "Education 2 - Years", type: "text", placeholder: "2013 – 2015" },
      { name: "edu2_degree", label: "Education 2 - Degree", type: "text", placeholder: "M.Sc. in Computer Science" },
      { name: "edu2_school", label: "Education 2 - School", type: "text", placeholder: "Springfield University" },
      { name: "edu3_years", label: "Education 3 - Years", type: "text", placeholder: "2009 – 2013" },
      { name: "edu3_degree", label: "Education 3 - Degree", type: "text", placeholder: "B.Sc. in Mathematics" },
      { name: "edu3_school", label: "Education 3 - School", type: "text", placeholder: "Lincoln College" },
      { name: "awards_heading", label: "Awards Heading", type: "text", placeholder: "Awards" },
      { name: "award1", label: "Award 1", type: "text", placeholder: "2019 – Outstanding Research Award, Springfield University" },
      { name: "award2", label: "Award 2", type: "text", placeholder: "2017 – Best Paper Award, IEEE Cloud Conference" },
      { name: "award3", label: "Award 3", type: "text", placeholder: "2015 – Dean’s List, Springfield University" },
      { name: "awards", label: "Awards Bullets", type: "bullets", placeholder: "Add awards", repeatable: true },
      { name: "skills_heading", label: "Technical Skills Heading", type: "text", placeholder: "Technical Skills" },
      { name: "skills_programming", label: "Skills - Programming", type: "text", placeholder: "Python, Java, C++, JavaScript, R" },
      { name: "skills_frameworks", label: "Skills - Frameworks", type: "text", placeholder: "React, Node.js, TensorFlow, PyTorch" },
      { name: "skills_tools", label: "Skills - Tools", type: "text", placeholder: "Git, Docker, AWS, GCP, SQL" },
      { name: "skills", label: "Technical Skills Bullets", type: "bullets", placeholder: "Add skills", repeatable: true },
      { name: "communication_heading", label: "Communication Skills Heading", type: "text", placeholder: "Communication Skills" },
      { name: "comm_conferences", label: "Communication - Conferences", type: "text", placeholder: "Speaker at PyCon 2019, IEEE Cloud 2017" },
      { name: "comm_publications", label: "Communication - Publications", type: "text", placeholder: "5 peer-reviewed journal articles" },
      { name: "comm_languages", label: "Communication - Languages", type: "text", placeholder: "English (native), Spanish (fluent)" },
      { name: "strengths_heading", label: "Professional Strengths Heading", type: "text", placeholder: "Professional Strengths" },
      { name: "strength_leadership", label: "Strength - Leadership", type: "text", placeholder: "Experience managing cross-functional teams" },
      { name: "strength_analytical", label: "Strength - Analytical Thinking", type: "text", placeholder: "Strong problem-solving and data analysis skills" },
    ],
    dummy: {
      // ...existing code...
    },
    fieldsPerPage: 10,
  },
  {
    name: "Sidebar (Template 3)",
    component: ResumeTemplate3,
    fields: [
      { name: "name", label: "Full Name", type: "text", placeholder: "Debarghya Das" },
      { name: "website", label: "Website", type: "text", placeholder: "http://debarghyadas.com" },
      { name: "email", label: "Email", type: "email", placeholder: "dd367@cornell.edu" },
      { name: "phone", label: "Phone", type: "tel", placeholder: "607.379.5733" },
      { name: "education_heading", label: "Education Heading", type: "text", placeholder: "EDUCATION" },
      { name: "edu1_school", label: "Education 1 - School", type: "text", placeholder: "CORNELL UNIVERSITY" },
      { name: "edu1_degree", label: "Education 1 - Degree", type: "text", placeholder: "MEng in Computer Science" },
      { name: "edu1_date", label: "Education 1 - Date", type: "text", placeholder: "Expected Dec 2014 | Ithaca, NY" },
      { name: "edu1_gpa", label: "Education 1 - GPA", type: "text", placeholder: "CUM. GPA: N/A" },
      { name: "edu2_degree", label: "Education 2 - Degree", type: "text", placeholder: "BS in Computer Science" },
      { name: "edu2_date", label: "Education 2 - Date", type: "text", placeholder: "Expected May 2014 | Ithaca, NY" },
      { name: "edu2_honors", label: "Education 2 - Honors", type: "text", placeholder: "Dean’s List (All Semesters)" },
      { name: "edu2_gpa", label: "Education 2 - GPA", type: "text", placeholder: "CUM. GPA: 3.9 / 4.0" },
      { name: "edu2_major_gpa", label: "Education 2 - Major GPA", type: "text", placeholder: "Major GPA: 3.94 / 4.0" },
      { name: "edu3_school", label: "Education 3 - School", type: "text", placeholder: "LA MARTINIERE FOR BOYS" },
      { name: "edu3_date", label: "Education 3 - Date", type: "text", placeholder: "Grad. May 2011 | Kolkata, India" },
      { name: "links_heading", label: "Links Heading", type: "text", placeholder: "LINKS" },
      { name: "link_github", label: "Link - Github", type: "text", placeholder: "Github:// deedyas" },
      { name: "link_linkedin", label: "Link - LinkedIn", type: "text", placeholder: "LinkedIn:// debarghyadas" },
      { name: "link_youtube", label: "Link - YouTube", type: "text", placeholder: "YouTube:// DeedyDash007" },
      { name: "link_twitter", label: "Link - Twitter", type: "text", placeholder: "Twitter:// @debarghya_das" },
      { name: "link_quora", label: "Link - Quora", type: "text", placeholder: "Quora:// Debarghya-Das" },
      { name: "links", label: "Links Bullets", type: "bullets", placeholder: "Add links", repeatable: true },
      { name: "coursework_heading", label: "Coursework Heading", type: "text", placeholder: "COURSEWORK" },
      { name: "cw_grad1", label: "Coursework Graduate 1", type: "text", placeholder: "Advanced Machine Learning" },
      { name: "cw_grad2", label: "Coursework Graduate 2", type: "text", placeholder: "Open Source Software Engineering" },
      { name: "cw_grad3", label: "Coursework Graduate 3", type: "text", placeholder: "Advanced Interactive Graphics" },
      { name: "cw_grad4", label: "Coursework Graduate 4", type: "text", placeholder: "Compilers + Practicum" },
      { name: "cw_grad5", label: "Coursework Graduate 5", type: "text", placeholder: "Cloud Computing" },
      { name: "cw_ug1", label: "Coursework Undergraduate 1", type: "text", placeholder: "Information Retrieval" },
      { name: "cw_ug2", label: "Coursework Undergraduate 2", type: "text", placeholder: "Operating Systems" },
      { name: "cw_ug3", label: "Coursework Undergraduate 3", type: "text", placeholder: "Artificial Intelligence + Practicum" },
      { name: "cw_ug4", label: "Coursework Undergraduate 4", type: "text", placeholder: "Functional Programming" },
      { name: "cw_ug5", label: "Coursework Undergraduate 5", type: "text", placeholder: "Computer Graphics + Practicum" },
      { name: "coursework", label: "Coursework Bullets", type: "bullets", placeholder: "Add coursework", repeatable: true },
      { name: "skills_heading", label: "Skills Heading", type: "text", placeholder: "SKILLS" },
      { name: "skills_5000", label: "Skills - Over 5000 lines", type: "text", placeholder: "Over 5000 lines:" },
      { name: "skills_5000_list1", label: "Skills - 5000 List 1", type: "text", placeholder: "Java , Shell , JavaScript , Matlab" },
      { name: "skills_5000_list2", label: "Skills - 5000 List 2", type: "text", placeholder: "OCaml , Python , Rails , LaTeX{}" },
      { name: "skills_1000", label: "Skills - Over 1000 lines", type: "text", placeholder: "Over 1000 lines:" },
      { name: "skills_1000_list", label: "Skills - 1000 List", type: "text", placeholder: "C , C++ , CSS , PHP , Assembly" },
      { name: "skills_familiar", label: "Skills - Familiar", type: "text", placeholder: "Familiar: AS3 , iOS , Android , MySQL" },
      { name: "skills", label: "Skills Bullets", type: "bullets", placeholder: "Add skills", repeatable: true },
      { name: "exp_heading", label: "Experience Heading", type: "text", placeholder: "EXPERIENCE" },
      { name: "exp1_company", label: "Experience 1 - Company", type: "text", placeholder: "COURSERA | KPCB Fellow + Software Engineering Intern" },
      { name: "exp1_dates", label: "Experience 1 - Dates", type: "text", placeholder: "Expected June 2014 – Sep 2014 | Mountain View, CA" },
      { name: "exp1_bullet1", label: "Experience 1 - Bullet 1", type: "text", placeholder: "• 52 out of 2500 applicants chosen to be a KPCB Fellow 2014." },
      { name: "exp1_bullets", label: "Experience 1 Bullets", type: "bullets", placeholder: "Add bullet points for Experience 1", repeatable: true },
      { name: "exp2_company", label: "Experience 2 - Company", type: "text", placeholder: "GOOGLE | Software Engineering Intern" },
      { name: "exp2_dates", label: "Experience 2 - Dates", type: "text", placeholder: "May 2013 – Aug 2013 | Mountain View, CA" },
      { name: "exp2_bullet1", label: "Experience 2 - Bullet 1", type: "text", placeholder: "Worked on YouTube Captions using JS and Python to implement full stack auto-captioning." },
      { name: "exp2_bullet2", label: "Experience 2 - Bullet 2", type: "text", placeholder: "Created a backbone.js-like framework for the Captions editor." },
      { name: "exp2_bullet3", label: "Experience 2 - Bullet 3", type: "text", placeholder: "Reviewed, perfected, and pushed all code to production." },
      { name: "exp3_company", label: "Experience 3 - Company", type: "text", placeholder: "PHABRICATOR | Open Source Contributor & Team Leader" },
      { name: "exp3_dates", label: "Experience 3 - Dates", type: "text", placeholder: "Jan 2013 – May 2013 | Palo Alto, CA & Ithaca, NY" },
      { name: "exp3_bullet1", label: "Experience 3 - Bullet 1", type: "text", placeholder: "Created Meme generator, Lispium, and more in PHP and Shell." },
      { name: "exp3_bullet2", label: "Experience 3 - Bullet 2", type: "text", placeholder: "Led team from MIT, Cornell, London, and U Helsinki." },
      { name: "research_heading", label: "Research Heading", type: "text", placeholder: "RESEARCH" },
      { name: "research1_title", label: "Research 1 - Title", type: "text", placeholder: "CORNELL ROBOT LEARNING LAB | Head Undergrad Research" },
      { name: "research1_dates", label: "Research 1 - Dates", type: "text", placeholder: "Jan 2014 – Present | Ithaca, NY" },
      { name: "research1_desc", label: "Research 1 - Description", type: "text", placeholder: "Worked with Ashesh Jain and Prof Ashutosh Saxena to create Planet, a tool using large-scale preference feedback." },
      { name: "research2_title", label: "Research 2 - Title", type: "text", placeholder: "CORNELL PHONETICS LAB | Head Undergraduate Researcher" },
      { name: "research2_dates", label: "Research 2 - Dates", type: "text", placeholder: "Mar 2012 – May 2013 | Ithaca, NY" },
      { name: "research2_desc", label: "Research 2 - Description", type: "text", placeholder: "Led development of QuickTongue with Prof Sam Tilsen." },
      { name: "awards_heading", label: "Awards Heading", type: "text", placeholder: "AWARDS" },
      { name: "award1", label: "Award 1", type: "text", placeholder: "2014: Top 52/2500 – KPCB Engineering Fellow" },
      { name: "award2", label: "Award 2", type: "text", placeholder: "2014: Microsoft Coding Competition Finalist" },
      { name: "award3", label: "Award 3", type: "text", placeholder: "2013: CS 3410 Cache Race Bot Tournament" },
      { name: "award4", label: "Award 4", type: "text", placeholder: "2012: CS 3110 Biannual Intra-Class Bot Tournament" },
      { name: "award5", label: "Award 5", type: "text", placeholder: "2011: INMO Finalist" },
      { name: "awards", label: "Awards Bullets", type: "bullets", placeholder: "Add awards", repeatable: true },
      { name: "societies_heading", label: "Societies Heading", type: "text", placeholder: "SOCIETIES" },
      { name: "society1", label: "Society 1", type: "text", placeholder: "2014: Tau Beta Pi Engineering Honor Society" },
      { name: "society2", label: "Society 2", type: "text", placeholder: "2012: Golden Key International Honour Society" },
      { name: "society3", label: "Society 3", type: "text", placeholder: "2012: National Society of Collegiate Scholars" },
    ],
    dummy: {
      // ...existing code...
    },
    fieldsPerPage: 10,
  }
];

export default templates;
