import { FeedbackButton } from "@/components/feedback";
import { AppHeader } from "@/components/layout/app-header";
import ClientAppWrapper from "@/components/layout/AppClientWrapper";
import { GoogleAnalytics } from "@/components/shared/GoogleAnalytics";
import { createClient } from "@/utils/supabase/server";
import { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  metadataBase: new URL("https://resumy.live"),
  title: {
    default: "Resumy - #1 Free AI Resume Builder | No Paywall, No Subscription, No Credit Card",
    template: "%s | Resumy - Free AI Resume Builder"
  },
  description: "The best free AI resume builder — create professional ATS-optimized resumes in minutes. Unlike Zety, Novoresume, and Resume.io that charge you to download, Resumy is 100% free forever. No hidden fees, no watermarks, no credit card required. Start building today!",
  applicationName: "Resumy",
  keywords: [
    // ── Short / head keywords ─────────────────────────────────────────────────
    "resume builder",
    "free resume builder",
    "ai resume builder",
    "resume maker",
    "resume templates",
    "online resume builder",
    "cv maker",
    "ats resume",
    "resume creator",
    "resume generator",
    "resume writer",
    "resume tool",
    "cv builder",
    "cv creator",
    "cv templates",
    "resume format",
    "resume design",
    "professional resume",
    "create resume",
    "resume app",

    // ── Medium keywords ───────────────────────────────────────────────────────
    "free resume maker",
    "free cv maker",
    "free resume templates",
    "resume builder free",
    "ats resume builder",
    "ats friendly resume",
    "ats resume checker",
    "resume builder online",
    "best resume builder",
    "ai resume maker",
    "modern resume builder",
    "resume builder 2025",
    "resume builder no sign up",
    "resume builder no credit card",
    "free resume download",
    "free professional resume",
    "create cv online",
    "resume builder open source",
    "online resume builder",
    "resume writing",
    "resume creator",
    "digital resume",
    "modern resume",
    "resume design",
    "resume scanner",
    "resume optimization",
    
    // Job search related
    "job application",
    "career builder",
    "job search",
    "hiring tools",
    "job hunting",
    "career development",
    "employment tools",
    "job seeker",
    "career advancement",
    "professional development",
    "job placement",
    "career coaching",
    
    // Industry specific
    "tech resume",
    "software engineer resume",
    "engineering resume",
    "IT resume",
    "developer resume",
    "programmer resume",
    "data scientist resume",
    "marketing resume",
    "sales resume",
    "finance resume",
    "accounting resume",
    "healthcare resume",
    "nursing resume",
    "teacher resume",
    "manager resume",
    "executive resume",
    "startup resume",
    "remote work resume",
    
    // AI and technology features
    "AI powered resume",
    "artificial intelligence resume",
    "machine learning resume",
    "automated resume builder",
    "smart resume maker",
    "intelligent resume creator",
    "AI resume assistant",
    "resume AI tool",
    "chatgpt resume",
    "AI resume optimization",
    "automated resume writing",
    
    // ATS and optimization
    "ATS friendly resume",
    "applicant tracking system",
    "ATS compliant resume",
    "ATS resume checker",
    "resume ATS optimization",
    "keyword optimization",
    "resume scoring",
    "ATS scanner",
    "resume parsing",
    "ATS resume format",
    
    // Format and design
    "resume format",
    "CV maker",
    "curriculum vitae",
    "professional CV",
    "resume layout",
    "resume structure",
    "clean resume design",
    "minimalist resume",
    "creative resume",
    "executive resume format",
    "chronological resume",
    "functional resume",
    "combination resume",
    "modern CV template",
    "professional resume template",
    
    // Features and benefits
    "free resume download",
    "resume pdf",
    "instant resume",
    "quick resume builder",
    "easy resume maker",
    "simple resume creator",
    "resume editor",
    "resume customization",
    "resume personalization",
    "tailored resume",
    "custom resume",
    "professional resume service",
    
    // Career levels
    "entry level resume",
    "graduate resume",
    "student resume",
    "internship resume",
    "senior level resume",
    "executive level resume",
    "career change resume",
    "first job resume",
    "experienced professional resume",
    
    // Additional 100+ Core Keywords for Resume & Resume Builder
    "resume writing service",
    "resume template download",
    "professional resume help",
    "resume examples by industry",
    "resume format guide",
    "CV template free",
    "resume skills section",
    "resume objective examples",
    "resume summary examples",
    "modern resume design",
    "creative resume templates",
    "executive resume samples",
    "resume cover letter",
    "resume keywords list",
    "resume tips 2025",
    "resume best practices",
    "resume writing tips",
    "resume layout design",
    "professional CV templates",
    "resume builder software",
    "online CV maker",
    "digital resume creator",
    "resume portfolio builder",
    "interactive resume maker",
    "video resume creator",
    "infographic resume maker",
    "resume website builder",
    "personal branding resume",
    "visual resume creator",
    "resume analytics tool",
    "resume tracking system",
    "resume performance metrics",
    "resume success rate",
    "resume interview scheduler",
    "job application tracker",
    "career portfolio builder",
    "professional profile creator",
    "LinkedIn resume sync",
    "social media resume",
    "networking resume tools",
    "career advancement tools",
    "professional development tracker",
    "skill assessment resume",
    "competency based resume",
    "achievement focused resume",
    "results driven resume",
    "quantified resume maker",
    "impact resume creator",
    "performance resume builder",
    "leadership resume templates",
    "management resume maker",
    "C-suite resume builder",
    "VP level resume creator",
    "director resume templates",
    "senior manager resume",
    "team leader resume maker",
    "supervisor resume builder",
    "coordinator resume templates",
    "specialist resume creator",
    "analyst resume maker",
    "consultant resume builder",
    "freelancer resume templates",
    "contractor resume creator",
    "remote worker resume",
    "digital nomad resume",
    "startup founder resume",
    "entrepreneur resume maker",
    "business owner resume",
    "CEO resume builder",
    "CTO resume templates",
    "CFO resume creator",
    "CMO resume maker",
    "CHRO resume builder",
    "product manager resume",
    "program manager resume",
    "project coordinator resume",
    "scrum master resume",
    "agile coach resume",
    "business analyst resume",
    "data analyst resume",
    "research scientist resume",
    "lab technician resume",
    "clinical researcher resume",
    "medical device resume",
    "pharmaceutical resume",
    "biotechnology resume",
    "healthcare administrator resume",
    "hospital manager resume",
    "medical assistant resume",
    "physician assistant resume",
    "nurse practitioner resume",
    "registered nurse resume",
    "licensed practical nurse resume",
    "certified nursing assistant resume",
    "medical technologist resume",
    "radiologic technologist resume",
    "physical therapist resume",
    "occupational therapist resume",
    "speech therapist resume",
    "mental health counselor resume",
    "social worker resume",
    "case manager resume",
    "human resources resume",
    "talent acquisition resume",
    "recruiter resume maker",
    "training specialist resume",
    "learning developer resume",
    "instructional designer resume",
    "curriculum developer resume",
    "education administrator resume",
    "school principal resume",
    "academic dean resume",
    "university professor resume",
    "research professor resume",
    "adjunct faculty resume",
    "graduate student resume",
    "postdoc researcher resume",

    // Competitor alternative keywords — people searching for free options
    "free alternative to Zety",
    "Zety free alternative resume builder",
    "free alternative to Novoresume",
    "Novoresume free alternative",
    "free alternative to Resume.io",
    "Resume.io free alternative",
    "free alternative to Kickresume",
    "free alternative to Canva resume builder",
    "free alternative to LinkedIn resume builder",
    "free alternative to Indeed resume builder",
    "free resume builder without watermark",
    "resume builder free download PDF no watermark",
    "resume builder no subscription needed",
    "resume builder no credit card",
    "resume builder completely free",
    "resume builder 100 percent free",
    "free resume builder no sign up required",
    "best resume builder that is actually free",
    "resume builder that doesn't charge to download",
    "open source resume builder free",
    "resume builder free forever",

    // ── Trending 2025 ─────────────────────────────────────────────────────────
    "ai resume builder 2025",
    "best free resume builder 2025",
    "best resume format 2025",
    "chatgpt resume builder",
    "ai generated resume free",
    "resume builder with chatgpt",
    "free resume builder india",
    "free resume builder uk",
    "free resume builder canada",
    "free resume builder australia",
    "best resume builder for india",
    "resume builder for naukri",
    "resume for remote jobs 2025",
    "tech resume 2025",
    "free resume builder reddit",

    // ── How-to longtail keywords ───────────────────────────────────────────────
    "how to make a resume for free",
    "how to create a professional resume",
    "how to build a resume online free",
    "how to write a resume step by step",
    "how to make an ats friendly resume",
    "how to pass ats with your resume",
    "how to make a resume with no experience",
    "how to write a resume summary",
    "how to write a resume objective",
    "what to put on a resume with no experience",
    "which resume builder is completely free",
    "which resume builder does not charge to download",
    "best free resume builder no hidden fees",

    // ── Use-case specific longtails ───────────────────────────────────────────
    "free resume builder for software engineers",
    "free resume builder for freshers india",
    "free resume builder for college students",
    "free resume builder for nurses",
    "free resume builder for teachers",
    "free resume builder for marketing jobs",
    "free resume builder no watermark pdf download",
    "free resume builder with cover letter",
    "ai resume builder free no subscription",
    "ai resume builder that writes for you",
    "create professional resume in 5 minutes free",
    "create ats friendly resume online free",
    "create resume online free no sign up",
    "build resume for free and download as pdf",
    "make resume online free download pdf",
    "resume template free download for freshers",
    "ats resume format free download",
    "free resume builder for international jobs",
    "free resume builder for government jobs",
    "open source free resume builder with ai",
    "resume builder free forever no hidden fees",
    "better than zety resume builder free",
    "free resume download without zety subscription",
    "resume builder with no paywall"
  ],
  authors: [{ name: "Resumy Team", url: "https://resumy.live" }],
  creator: "Resumy",
  publisher: "Resumy",
  category: "Business",
  classification: "Resume Building Software",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon/favicon-96x96.png",
    apple: "/favicon/apple-touch-icon.png",
    other: [
      {
        rel: "icon",
        type: "image/svg+xml",
        url: "/favicon/favicon.svg",
      },
      {
        rel: "mask-icon",
        url: "/favicon/favicon.svg",
        color: "#8B5CF6",
      },
      {
        rel: "image_src",
        url: "/logo.png",
      },
    ],
  },
  manifest: "/favicon/site.webmanifest",
  openGraph: {
    type: "website",
    siteName: "Resumy",
    title: "Resume Builder Free | Create Professional Resumes Online | Resumy",
    description: "Build professional ATS-optimized resumes for free with AI assistance. Create winning resumes in minutes with smart templates, keyword optimization, and expert guidance. Perfect for tech professionals, healthcare workers, finance experts, and all career levels. Get hired faster with resumes that pass applicant tracking systems.",
    url: "https://resumy.live",
    locale: "en_US",
    images: [
      {
        url: "/og.webp",
        width: 1200,
        height: 630,
        alt: "Resumy - Free AI Resume Builder",
        type: "image/webp",
      },
      {
        url: "/logo.png",
        width: 512,
        height: 512,
        alt: "Resumy Logo",
        type: "image/png",
      },
    ],
  },  twitter: {
    card: "summary_large_image",
    site: "@resumy",
    creator: "@resumy",
    title: "Resume Builder Free | Create Professional Resumes Online | Resumy",
    description: "Build professional ATS-optimized resumes for free with AI assistance. Perfect for software engineers, healthcare professionals, marketing experts, and all career levels. Start building your winning resume today!",
    images: ["/og.webp"],
  },
  robots: {
    index: true,
    follow: true,
    noarchive: false,
    nosnippet: false,
    noimageindex: false,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      noarchive: false,
      nosnippet: false,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  alternates: {
    canonical: "https://resumy.live",
  },
  other: {
    "google-site-verification": "your-google-verification-code", // Replace with actual verification code
    "msvalidate.01": "your-bing-verification-code", // Replace with actual verification code
    "pinterest-domain-verify": "your-pinterest-verification-code", // Replace with actual verification code
    "apple-mobile-web-app-title": "Resumy",
    "application-name": "Resumy",
    "msapplication-TileColor": "#8B5CF6",
    "theme-color": "#8B5CF6",
  },
  // verification: {
  //   google: "google-site-verification-code", // Replace with actual verification code
  //   yandex: "yandex-verification-code", // Replace with actual verification code  
  //   bing: "bing-verification-code", // Replace with actual verification code
  // },
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Additional logo-specific meta tags */}
        <link rel="image_src" href="/logo.png" />
        <meta property="og:logo" content="https://resumy.live/logo.png" />
        <meta name="msapplication-TileImage" content="/logo.png" />
      </head>
      <body className={`${inter.className} antialiased`} suppressHydrationWarning>
        <GoogleAnalytics />
        <ClientAppWrapper>
          <div className="relative min-h-screen flex flex-col">
            {user && <AppHeader />}
            {/* Main content */}
            <main className={`flex-1 bg-black ${user ? 'pt-16' : ''}`}>
              {children}
            </main>
          </div>
          {/* Floating Feedback Button */}
          <FeedbackButton />
        </ClientAppWrapper>
      </body>
    </html>
  );
}
